name: Auto Delete Snapshots
version: 0.0.1
slug: autodelete
description: Container to automatically delete backups older than set number of days
url: https://github.com/jak119/hassio-backup-azure-blob/tree/main/autodelete
startup: once
# image: ghcr.io/jak119/{arch}-hassio-autodelete
init: false
options:
  daystokeep: 7
schema:
  daystokeep: int(1,)
map:
  - backup:rw
arch:
  - amd64
  - armv7
  - i386
  - aarch64
