name: Backup to Azure Blob - Azcopy
version: 1.1.0
slug: azcopy
description: Container to copy Hassio backups to an Azure Storage Account using Azcopy
url: https://github.com/jak119/hassio-backup-azure-blob/tree/main/azcopy
startup: once
image: ghcr.io/jak119/{arch}-hassio-azcopy
init: false
options:
  sas_token: ""
schema:
  sas_token: url
  delete: "bool?"
map:
  - backup:ro
arch:
  - amd64
  - armv7
  - i386
  - aarch64
