name: Backup to Azure Blob - Azcopy
version: d41d8cd98f00b204e9800998ecf8427e
slug: azcopy
description: Container to copy Hassio backups to an Azure Storage Account
url: https://github.com/jak119/hassio-backup-azcopy
startup: once
image: ghcr.io/jak119/{arch}-hassio-azcopy
init: false
options:
  sas_token: ""
schema:
  sas_token: url
  delete: "bool?"
map:
  - backup:ro
arch:
  - amd64
  - armv7
  - i386
  - aarch64
