name: Backup to Azure Blob - Azcopy
version: 0.0.10
slug: azcopy
description: Container to copy Hassio backups to an Azure Storage Account
url: https://github.com/jak119/hassio-backup-azcopy
startup: once
# image: ghcr.io/jak119/{arch}-hassio-azcopy
init: false
options:
  sas_token: ""
  delete-destination: false
schema:
  sas_token: url
  delete-destination: "bool"
map:
  - backup:ro
arch:
  - amd64
  - armv7
  - i386
  - aarch64
advanced: true
stage: experimental
