build_from:
  aarch64: "aarch64-base-python:3.10"
  armv7: "armv7-base-python:3.10"
  armhf: "armhf-base-python:3.10"
  amd64: "amd64-base-python:3.10"
  i386: "i386-base-python:3.10"
codenotary:
  signer: notary@home-assistant.io
  base_image: notary@home-assistant.io
