name: Backup to Azure Blob with Restic
version: 0.0.2
stage: deprecated
slug: restic_azure
description: Container to copy Hassio backups to an Azure Storage Account with Restic
url: https://github.com/jak119/hassio-backup-azure-blob/tree/main/restic
startup: once
image: ghcr.io/jak119/{arch}-hassio-azure-backup-restic
options:
  days_to_keep: 90
schema:
  storageaccount: "str"
  key: "password"
  containername: "str"
  folder: "match(^[^/].*)?"
  repopassword: "password"
  days_to_keep: "int"
map:
  - backup:ro
arch:
  - amd64
  - armv7
  - armhf
  - i386
  - aarch64
