build_from:
  aarch64: ghcr.io/hassio-addons/base-python/aarch64
  amd64: ghcr.io/hassio-addons/base-python/amd64
  armv7: ghcr.io/hassio-addons/base-python/armv7
  i386: ghcr.io/hassio-addons/base-python/i386
args:
  IMAGE_VERSION: "16.0.1"
