name: Azcopy Version

on:
  workflow_dispatch:
  schedule:
    - cron: "7 6 * * 6"

jobs:
  check:
    runs-on: ubuntu-latest
    name: Check latest version
    outputs:
      new-version: ${{steps.latest.outputs.latest}}
      update-avail: ${{steps.update.outputs.update-avail}}
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
      - name: Get latest Azcopy version
        id: latest
        run: |
          latest=$(curl -sLo- https://api.github.com/repos/Azure/azure-storage-azcopy/releases | jq -r '.[0].tag_name')
          echo "Latest version: $latest"
          echo "latest=$latest" >> $GITHUB_OUTPUT
      - name: Get current version of Azcopy in add-on
        id: current
        uses: mikefarah/yq@master
        with:
          cmd: yq '.args.AZCOPY_VERSION' 'azcopy/build.yaml'
      - name: Compare
        run: |
          echo "Latest version: ${{steps.latest.outputs.latest}}"
          echo "Current version: ${{steps.current.outputs.result}}"
      - name: Set Update flag
        id: update
        if: steps.latest.outputs.latest != steps.current.outputs.result
        run: echo "update-avail=true" >> $GITHUB_OUTPUT

  update:
    runs-on: ubuntu-latest
    name: Create a PR to update the version
    needs: check
    if: needs.check.outputs.update-avail == 'true'
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
      - name: Set new azcopy version in add-on build variables
        id: current
        uses: mikefarah/yq@master
        with:
          cmd: yq -i '.args.AZCOPY_VERSION = "${{needs.check.outputs.new-version}}"' 'azcopy/build.yaml'
      - name: Get current version of add-on
        id: current_addon_version
        uses: mikefarah/yq@master
        with:
          cmd: yq '.version' 'azcopy/config.yaml'
      - name: Bump add-on release version
        id: bump_version
        uses: christian-draeger/increment-semantic-version@1.1.0
        with:
          current-version: ${{ steps.current_addon_version.outputs.result }}
          version-fragment: "bug"
      - name: Display new version
        run: echo ${{ steps.bump_version.outputs.next-version }}
      - name: Set new add-on version
        uses: mikefarah/yq@master
        with:
          cmd: yq -i '.version = "${{steps.bump_version.outputs.next-version}}"' 'azcopy/config.yaml'
      - name: Add Change
        uses: natescherer/changelog-management-action@v1
        with:
          mode: addchange
          changeType: changed
          changeValue: Bump Azcopy to version ${{needs.check.outputs.new-version}}
          path: azcopy/CHANGELOG.md
      - name: Update Changelog for Release
        uses: natescherer/changelog-management-action@v1
        with:
          mode: release
          releaseVersion: ${{steps.bump_version.outputs.next-version}}
          path: azcopy/CHANGELOG.md
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v6.0.1
        with:
          commit-message: Bump to version ${{needs.check.outputs.new-version}}
          branch: azcopy/${{needs.check.outputs.new-version}}
          title: "Bump Azcopy version to ${{needs.check.outputs.new-version}}"
          draft: true
          labels: azcopy-version
