name: Azcopy Version

on:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    name: Check latest version
    outputs:
      new-version: ${{steps.latest.outputs.latest}}
      update-avail: ${{steps.update.outputs.update-avail}}
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
      - name: Get latest Azcopy version
        id: latest
        run: |
          latest=$(curl -sLo- https://api.github.com/repos/Azure/azure-storage-azcopy/releases | jq -r '.[0].tag_name')
          echo "Latest version: $latest"
          echo "latest=$latest" >> $GITHUB_OUTPUT
      - name: Get current version in add-on
        id: current
        uses: mikefarah/yq@master
        with:
          cmd: yq '.args.AZCOPY_VERSION' 'azcopy/build.yaml'
      - name: Compare
        run: |
          echo "Latest version: ${{steps.latest.outputs.latest}}"
          echo "Current version: ${{steps.current.outputs.result}}"
      - name: Set Update flag
        id: update
        if: steps.latest.outputs.latest != steps.current.outputs.result
        run: echo "update-avail=true" >> $GITHUB_OUTPUT

  update:
    runs-on: ubuntu-latest
    name: Initialize builds
    needs: check
    if: needs.check.outputs.update-avail == 'true'
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
      - name: Get current version in add-on
        id: current
        uses: mikefarah/yq@master
        with:
          cmd: yq w 'azcopy/build.yaml' '.args.AZCOPY_VERSION' '${{needs.check.outputs.new-version}}'
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: Bump to version ${{needs.check.outputs.new-version}}
          branch: azcopy/${{needs.check.outputs.new-version}}
          title: 'Bump Azcopy version to ${{needs.check.outputs.new-version}}'
          draft: true
