name: Update HA Files

on:
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  fetch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4
        with:
          path: addon
      - name: Checkout the Devcontainer repo
        uses: actions/checkout@v4
        with:
          repository: home-assistant/devcontainer
          path: devcontainer
      - name: Checkout the addons-example repo
        uses: actions/checkout@v4
        with:
          repository: home-assistant/addons-example
          path: addons-example

      # - name: Copy files into place for workflow
      #   run: |
      #     cp -avf ./addons-example/.github/* ./addon/.github

      - name: Copy files into place
        run: |
          cp -avf ./devcontainer/addons/devcontainer.json ./addon/.devcontainer/
          cp -avf ./devcontainer/addons/tasks.json ./addon/.vscode/

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          path: addon
          commit-message: Update HA dependencies
          title: Update HA dependencies
          branch: update-dependencies
