name: 'Test Build'

# on: [push, pull_request, workflow_dispatch]
on: 
  workflow_dispatch:
  push:
    branches-ignore: 
      - main

jobs:
  build:
    name: Test build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2
    - name: Test build
      uses: home-assistant/builder@master
      with:
        args: |
          --test \
          --all \
          --target . \
          --docker-hub jamisonkissh \
          --image {arch}-hassio-azure-backup
